version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/opt/mongo/data/db
    networks:
      - backend-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spider-container
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/spider
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mongodb_data:
